apiVersion: v1
kind: Service
metadata:
  name: pi-proxy-lb
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: persistentvolumes
=======
    kubernetes.courselabs.co: persistentvolumes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: pi-proxy
spec:
  ports:
    - port: 8010
      targetPort: http
      name: http
  selector:
    app: pi-proxy
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pi-proxy-np
  labels:
    app: pi-proxy
<<<<<<< HEAD
    kubernetes.azureauthority.in: persistentvolumes
=======
    kubernetes.courselabs.co: persistentvolumes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  ports:
    - port: 8010   
      targetPort: http 
      name: http
      nodePort: 30010
  selector:
    app: pi-proxy
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-proxy
  labels:
    app: pi-proxy
<<<<<<< HEAD
    kubernetes.azureauthority.in: persistentvolumes
=======
    kubernetes.courselabs.co: persistentvolumes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    matchLabels:
      app: pi-proxy
  template:
    metadata:
      labels:
        app: pi-proxy
        storage: container
    spec:
      containers:
        - image: nginx:1.18-alpine
          name: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: "/etc/nginx/"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx-configmap
