apiVersion: v1
kind: Service
metadata:
  name: pi-web-internal
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: persistentvolumes
=======
    kubernetes.courselabs.co: persistentvolumes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: pi-web
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: pi-web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  labels:
    app: pi-web
<<<<<<< HEAD
    kubernetes.azureauthority.in: persistentvolumes
=======
    kubernetes.courselabs.co: persistentvolumes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      containers:
        - image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: pi-web
          ports:
            - containerPort: 80
              name: http
