title: Azure Course Labs
markdown: kramdown
kramdown:
  parse_block_html: true
<<<<<<< HEAD
google_analytics: G-VRSCQMLV62
=======
google_analytics: G-TQNDKELFXN
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
