apiVersion: v1
kind: Pod
metadata:
  name: sleep
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: services
=======
    kubernetes.courselabs.co: services
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: sleep
spec:
  containers:
    - name: sleep
      image: kiamol/ch03-sleep