apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurable-lab
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: secrets
=======
    kubernetes.courselabs.co: secrets
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: configurable-lab
spec:
  selector:
    matchLabels:
      app: configurable-lab
  template:
    metadata:
      labels:
        app: configurable-lab
    spec:
      containers:
        - name: app
          image: sixeyed/configurable:21.04
          volumeMounts:
            - name: secret
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: secret
          secret:
            secretName: configurable-lab-secret-v2