apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurable
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: configmaps
=======
    kubernetes.courselabs.co: configmaps
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: configurable
spec:
  selector:
    matchLabels:
      app: configurable
  template:
    metadata:
      labels:
        app: configurable
    spec:
      containers:
        - name: app
          image: sixeyed/configurable:21.04
          envFrom:
            - configMapRef:
                name: configurable-env
          volumeMounts:
            - name: config-override
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config-override
          configMap:
            name: configurable-override
