apiVersion: v1
kind: Service
metadata:
  name: pi-np
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: troubleshooting
=======
    kubernetes.courselabs.co: troubleshooting
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    app: pi-web
  ports:
    - name: http
      port: 8020
      targetPort: http
      nodePort: 30020
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: pi-lb
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: troubleshooting
=======
    kubernetes.courselabs.co: troubleshooting
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    app: pi-web
  ports:
    - name: http
      port: 8020
      targetPort: http
  type: LoadBalancer