apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scp-keyvault-01
  labels: 
<<<<<<< HEAD
    azure.azureauthority.in: aks-apps
=======
    azure.courselabs.co: aks-apps
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: asset-manager
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: <identity-id>
    keyvaultName: <kv-name>
    objects:  |
      array:
        - |
          objectName: asset-manager-connectionstrings
          objectType: secret
          objectAlias: connectionstrings.json
    tenantId: <tenant-id>