apiVersion: v1
kind: Service
metadata:
  name: asset-manager-lb
  labels: 
<<<<<<< HEAD
    azure.azureauthority.in: aks-apps
=======
    azure.courselabs.co: aks-apps
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: asset-manager
spec:
  selector:
    app: asset-manager
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer