apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: ingress
=======
    kubernetes.courselabs.co: ingress
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.18-alpine
          name: nginx
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: content
          configMap:
            name: nginx-content