apiVersion: v1
kind: Service
metadata:
  name: nginx-internal
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: ingress
=======
    kubernetes.courselabs.co: ingress
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP