apiVersion: v1
kind: PersistentVolume
metadata:
  name: pi-proxy-pv
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: persistentvolumes
=======
    kubernetes.courselabs.co: persistentvolumes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: pi-proxy
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /volumes/pi-proxy
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: labs-pvc
            operator: Exists