apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-proxy-pvc-local
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: persistentvolumes
=======
    kubernetes.courselabs.co: persistentvolumes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: pi-proxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: ""
  volumeName: pi-proxy-pv