apiVersion: v1
kind: Service
metadata:
  name: whoami-np
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: deployments
=======
    kubernetes.courselabs.co: deployments
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: whoami
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8010
      targetPort: 80
      nodePort: 30010
  type: NodePort