apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: deployments
=======
    kubernetes.courselabs.co: deployments
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
        version: v1
    spec:
      containers:
        - name: app
          image: sixeyed/whoami:21.04