apiVersion: v1
kind: Pod
metadata:
  name: sleep
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: persistentvolumes
=======
    kubernetes.courselabs.co: persistentvolumes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  containers:
    - name: sleep
      image: kiamol/ch03-sleep
      volumeMounts:
        - name: node-root
          mountPath: /node-root
  volumes:
    - name: node-root
      hostPath:
        path: /
        type: Directory
      