apiVersion: v1
kind: Service
metadata:
  name: configurable-np
  namespace: configurable
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: namespaces
=======
    kubernetes.courselabs.co: namespaces
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    app: configurable
  ports:
    - name: http
      port: 8020
      targetPort: 80
      nodePort: 30020
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: configurable-lb
  namespace: configurable
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: namespaces
=======
    kubernetes.courselabs.co: namespaces
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    app: configurable
  ports:
    - name: http
      port: 8020
      targetPort: 80
  type: LoadBalancer