apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: troubleshooting
=======
    kubernetes.courselabs.co: troubleshooting
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  replicas: 0
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web-app
    spec:
      containers:
        - image: kiamol/ch05-pi-app
          command: ["donet", "Pi.Web.dll", "-m", "web"]
          name: web
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: "32"            
              memory: "128Gi"
          readinessProbe:
            tcpSocket:
              port: 8020
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthy
              port: 80
            periodSeconds: 30
            failureThreshold: 1