apiVersion: v1
kind: Service
metadata:
  name: whoami-lb
  namespace: whoami
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: namespaces
=======
    kubernetes.courselabs.co: namespaces
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8010
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-np
  namespace: whoami
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: namespaces
=======
    kubernetes.courselabs.co: namespaces
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8010
      targetPort: 80
      nodePort: 30010
  type: NodePort