apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurable
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: secrets
=======
    kubernetes.courselabs.co: secrets
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: configurable
spec:
  selector:
    matchLabels:
      app: configurable
  template:
    metadata:
      labels:
        app: configurable
    spec:
      containers:
        - name: app
          image: sixeyed/configurable:21.04         
          envFrom:
            - secretRef:
                name: configurable-env-encoded
