apiVersion: v1
kind: Pod
metadata:
  name: tls-cert-generator
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: ingress
=======
    kubernetes.courselabs.co: ingress
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  containers:
    - name: app
      image: kiamol/ch15-cert-generator
      env:
        - name: HOST_NAME
          value: default.local
        - name: SAN
          value: DNS:pi.local,DNS:whoami.local,DNS:configurable.local
