apiVersion: v1
kind: Service
metadata:
  name: rngapi-np
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: containerprobes
=======
    kubernetes.courselabs.co: containerprobes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    app: rngapi
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30045
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rngapi-lb
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: containerprobes
=======
    kubernetes.courselabs.co: containerprobes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    app: rngapi
  ports:
    - name: http
      port: 8040
      targetPort: 80
  type: LoadBalancer