apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: services
=======
    kubernetes.courselabs.co: services
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP