apiVersion: apps/v1
kind: Deployment
metadata:
  name: rngapi
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: containerprobes
=======
    kubernetes.courselabs.co: containerprobes
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rngapi
  template:
    metadata:
      labels:
        app: rngapi
    spec:
      containers:
        - name: app
          image: kiamol/ch03-numbers-api
          env:
            - name: FailAfterCallCount
              value: "1"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 5
            initialDelaySeconds: 10
            failureThreshold: 1
