apiVersion: v1
kind: ConfigMap
metadata:
  name: configurable-env
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: secrets
=======
    kubernetes.courselabs.co: secrets
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: configurable
data:
  Configurable__Release: 24.01.2
  Configurable__Environment: uat
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configurable-override
data:
  override.json: |-
    {
      "Features" : {
        "Caching" : true
      }
    }
