apiVersion: v1
kind: Service
metadata:
  name: configurable-np
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: secrets
=======
    kubernetes.courselabs.co: secrets
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: configurable
spec:
  selector:
    app: configurable
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30010
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: configurable-lb
  labels: 
<<<<<<< HEAD
    kubernetes.azureauthority.in: secrets
=======
    kubernetes.courselabs.co: secrets
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
    app: configurable
spec:
  selector:
    app: configurable
  ports:
    - name: http
      port: 8010
      targetPort: 80
  type: LoadBalancer