apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-lab-v1
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: deployments
=======
    kubernetes.courselabs.co: deployments
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami-lab
      version: v1
  template:
    metadata:
      labels:
        app: whoami-lab
        version: v1
    spec:
      containers:
        - name: app
          image: sixeyed/whoami:21.04
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-lab-v2
  labels:
<<<<<<< HEAD
    kubernetes.azureauthority.in: deployments
=======
    kubernetes.courselabs.co: deployments
>>>>>>> 294ba0192c4d7be6084b7914be1fecee6edd1552
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami-lab
      version: v2
  template:
    metadata:
      labels:
        app: whoami-lab
        version: v2
    spec:
      containers:
        - name: app
          image: sixeyed/whoami:21.04
          env:
            - name: WHOAMI_MODE
              value: q